# Generated by Django 4.0.1 on 2022-01-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.hall'),
        ),
    ]
