# Generated by Django 4.0.1 on 2022-01-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_hall_performance_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
