# Generated by Django 4.0.1 on 2022-01-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_play_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='play',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.author'),
        ),
    ]
