# Generated by Django 4.0.1 on 2022-02-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_author_alter_play_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(default=None),
        ),
    ]
