# Generated by Django 4.0.1 on 2022-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
        migrations.AddField(
            model_name='performance',
            name='price',
            field=models.FloatField(default=99.99),
        ),
    ]
