# Generated by Django 4.0.1 on 2022-02-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
